### ISSUE TITLE
CUSTOM_MODELS无法定义ChatGPT模型顺序

### ISSUE THREAD

**Issue by qingju32** [ChatGPTNextWebTeam/ChatGPT-Next-Web#3510]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭，如果没有提供下方的信息，我们无法定位你的问题。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
使用CUSTOM_MODELS自定义展示的模型，其中ChatGPT的模型没有按照变量的顺序展示，国产模型顺序正确。浏览器端尝试过“清除所有数据”按钮，没有变化；CUSTOM_MODELS变量尝试添加“-all”，没有变化。

**如何复现**
docker compose中添加下面的字段
CUSTOM_MODELS=-all,+gpt-3.5-turbo,-gpt-3.5-turbo-0301,-gpt-3.5-turbo-0613,+gpt-3.5-turbo-1106,-gpt-3.5-turbo-16k,-gpt-3.5-turbo-16k-0613,+gpt-4,-gpt-4-0314,-gpt-4-0613,+gpt-4-1106-preview,+gpt-4-vision-preview,+gpt-4-32k,-gpt-4-32k-0314,+gpt-4-32k-0613,+SparkDesk,+chatglm_turbo,+ERNIE-Bot,+ERNIE-Bot-turbo,+ERNIE-Bot-4,+qwen-turbo,+qwen-plus

**截图**
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/40858189/ac5711e5-1305-4662-bd73-4b4a7ce12678)

**一些必要的信息**
 - 系统：[Windows 11]
 - 浏览器： [Edge]
 - 版本： [v2.9.13]
 - 部署方式：[服务器docker部署]

**Comment by AndyX-Net** [comment]
Refer link:
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/3335

**Comment by qingju32** [comment]
> Refer link: #3335

I'm not sure. Is that the same question?

**Comment by Yidadaa** [comment]
顺序是随机的，也无意支持排序。
