### ISSUE TITLE
[Feature] 环境变量适配Pandora

### ISSUE THREAD

**Issue by Seigi-Liuling** [ChatGPTNextWebTeam/ChatGPT-Next-Web#3515]
目前环境变量BASE_URL仅适用于反代官方api接口的host，访问时强制路径为{BASE_URL}/api/openai，无法兼容PandoraNext

**Comment by FranzKafkaYu** [comment]
遇到了同样的问题，直接在Web设置中设置endpoint与通过BASE_URL环境变量设置时，表现不一样：
EndPoint && BASE_URL为`https://example.come/prefix`
通过EndPoint设置时，Web发送的请求如下：
```  
/prefix/v1/chat/completions
```   
通过BASE_URL设置时，Web发送的请求如下：  
```  
/prefix/v1/chat/completions?path=v1%2Fchat%2Fcompletions
```   

请问是否有办法解决该问题呢？

**Comment by zhangwengyu999** [comment]
Same problem, looking forward to the solution.

**Comment by zhangwengyu999** [comment]
I get the solution, change [the line 15 of the ./app/api/common.ts](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/blob/main/app/api/common.ts#L15) from 

```ts
let path = `${req.nextUrl.pathname}${req.nextUrl.search}`.replaceAll(
```
 to 

```ts
let path = `${req.nextUrl.pathname}`.replaceAll(
```
where the `${req.nextUrl.search}` is removed, so Proxy path will become `v1/chat/completions` only.

It works for me.

**Comment by jackeyzzz12138** [comment]
> I get the solution, change [the line 15 of the ./app/api/common.ts](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/blob/main/app/api/common.ts#L15) from
> 
> ```ts
> let path = `${req.nextUrl.pathname}${req.nextUrl.search}`.replaceAll(
> ```
> 
> to
> 
> ```ts
> let path = `${req.nextUrl.pathname}`.replaceAll(
> ```
> 
> where the `${req.nextUrl.search}` is removed, so Proxy path will become `v1/chat/completions` only.
> 
> It works for me.

Thanks for your solution, it works out!
