### ISSUE TITLE
[Bug] azure 3.5 turbo 提示404 Resource not found

### ISSUE THREAD

**Issue by kerio1989** [ChatGPTNextWebTeam/ChatGPT-Next-Web#3516]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Servere

版本：网页版
响应: {
  "error": {
    "code": "404",
    "message": "Resource not found"
  }
}
配置
url: https://zjhgpt4.openai.azure.com/zjh
api -version 2023-08-01-preview
模型： gpt 3.5 turbo

**Additional Logs**
Add any logs about the problem here.

**Comment by zhangjunhao1993** [comment]
<img width="1216" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/48510454/b075fec3-ec1f-4112-8f48-c33caeb4fc5d">

**Comment by zyjia** [comment]
我的3.5模型部署成功，gpt4b部署返回的错误与你相同

**Comment by zhangjunhao1993** [comment]
> 我的3.5模型部署成功，gpt4部署返回的错误与你相同.

我现在直接用azure部署了，直接生成web界面。
<img width="697" alt="image" src="https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/48510454/06930df3-6b88-4a81-934f-068d2e763a60">

**Comment by zyjia** [comment]
> > 我的3.5模型部署成功，gpt4部署返回的错误与你相同.
> 
> 我现在直接用azure部署了，直接生成web界面。 <img alt="image" width="697" src="https://private-user-images.githubusercontent.com/48510454/290387372-06930df3-6b88-4a81-934f-068d2e763a60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDQ1MzksIm5iZiI6MTcwMjU0NDIzOSwicGF0aCI6Ii80ODUxMDQ1NC8yOTAzODczNzItMDY5MzBkZjMtNmI4OC00YTgxLTkzNGYtMDY4ZDJlNzYzYTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA4NTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YmJiM2UwY2Y4MzNmMzQxMmM2YzQwNzFmMzAyYzQ1MmQ0ZmJjNmZkMTdiNjA3MDYzOTI2Zjg5NjU3NWY2YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N-GxrEeOL7yceAdVhrZTW6gQThty2OkmOJCdYy0etfM">

大哥，教教如何做

**Comment by kerio1989** [comment]
> 大哥，教教如何做

去聊天操场，上面有个部署至，然后点击新的web应用，，应用选择basic 1,差不多15分钟部署好
