### ISSUE TITLE
[Bug] Azure api在使用 gpt-4-vision-preview模型时，返回消息不完整

### ISSUE THREAD

**Issue by bob0627** [ChatGPTNextWebTeam/ChatGPT-Next-Web#3518]
使用 [cf-openai-azure-proxy](https://github.com/haibbo/cf-openai-azure-proxy) 插件中转azure的api，使用gpt-4-vision-preview模型时，返回消息不完整，每次都只是几个或者十几个单词就停止响应了。

![微信截图_20231213171623](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/14833035/da2c3494-e179-4081-aa74-2a8a55d09795)

**Comment by C-Dragon8** [comment]
兄弟，我也遇到了此问题，现在你解决了吗？

**Comment by Yidadaa** [comment]
和 vision 的默认 max_tokens 设置有关，请等待项目支持 vision 模型。

**Comment by daidi** [comment]
> 和 vision 的默认 max_tokens 设置有关，请等待项目支持 vision 模型。

when?
