### ISSUE TITLE
[Feature] 增加 Gemini Pro API 支持

### ISSUE THREAD

**Issue by devyujie** [ChatGPTNextWebTeam/ChatGPT-Next-Web#3522]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
、

**你想要什么功能或者有什么建议？**
增加 [Gemini Pro API](https://ai.google.dev/) 支持，目前免费试用，[文档](https://ai.google.dev/tutorials/node_quickstart?hl=zh-cn)在这。

**有没有可以参考的同类竞品？**
、

**其他信息**
[参考推文](https://x.com/dotey/status/1735064009974431884?s=20)

**Comment by H0llyW00dzZ** [comment]
read this [Bug] Repo it's bugged since switch to organization not a personal #3521

**Comment by y1324** [comment]
现在好像没什么动静

**Comment by zaleGZL** [comment]
感觉这 Gemini Pro 有点弱 😂

**Comment by Yidadaa** [comment]
请使用 one-api https://github.com/songquanpeng/one-api
