### ISSUE TITLE
[Bug] Cannot sync upstream, github action reports error

### ISSUE THREAD

**Issue by ysl2** [ChatGPTNextWebTeam/ChatGPT-Next-Web#3523]
![image](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/39717545/f39da7f9-e38d-43af-9811-e5094d0e6be1)

---

![image](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/39717545/8ba1b340-ff15-4127-ae2c-8d53f987e02b)

**Comment by H0llyW00dzZ** [comment]
[Bug] Repo it's bugged since switch to organization not a personal #3521

**Comment by Yidadaa** [comment]
#3521
