### ISSUE TITLE
API接口报错

### ISSUE THREAD

**Issue by maojianyou** [ChatGPTNextWebTeam/ChatGPT-Next-Web#3530]
![image](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/55315920/f865c38f-d0dc-4431-b8dd-286796e49ba4)
可能API是不是需要收费，能否支持accessToken访问

**Comment by Yidadaa** [comment]
余额过期了，与项目无关，如果你需要 sess token，请考虑 pandora-next 项目。
