### ISSUE TITLE
[Bug]vercel部分图片加载不到但是部署网站可以访问，开魔法后才正常

### ISSUE THREAD

**Issue by sunsky89757** [ChatGPTNextWebTeam/ChatGPT-Next-Web#3531]
![111](https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/113254524/8bd291aa-f584-4e5c-a06e-928dcbc21d0a)
如图

**Comment by Yidadaa** [comment]
看起来是 emoji 库的 cdn 炸了，需要更新一下 cdn 地址。

**Comment by Yidadaa** [comment]
https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/blob/cae4655785837696f6af3022c916035e43298d46/app/components/emoji.tsx#L12
